<a href="javascript:grin(' :?: ')"><img src="https://cdn.peanoo.com/ASkyo/images/smilies/icon_question.gif" alt="" /></a>
<a href="javascript:grin(' :razz: ')"><img src="https://cdn.peanoo.com/ASkyo/images/smilies/icon_razz.gif" alt="" /></a>
<a href="javascript:grin(' :sad: ')"><img src="https://cdn.peanoo.com/ASkyo/images/smilies/icon_sad.gif" alt="" /></a>
<a href="javascript:grin(' :evil: ')"><img src="https://cdn.peanoo.com/ASkyo/images/smilies/icon_evil.gif" alt="" /></a>
<a href="javascript:grin(' :!: ')"><img src="https://cdn.peanoo.com/ASkyo/images/smilies/icon_exclaim.gif" alt="" /></a>
<a href="javascript:grin(' :smile: ')"><img src="https://cdn.peanoo.com/ASkyo/images/smilies/icon_smile.gif" alt="" /></a>
<a href="javascript:grin(' :oops: ')"><img src="https://cdn.peanoo.com/ASkyo/images/smilies/icon_redface.gif" alt="" /></a>
<a href="javascript:grin(' :grin: ')"><img src="https://cdn.peanoo.com/ASkyo/images/smilies/icon_biggrin.gif" alt="" /></a>
<a href="javascript:grin(' :eek: ')"><img src="https://cdn.peanoo.com/ASkyo/images/smilies/icon_surprised.gif" alt="" /></a>
<a href="javascript:grin(' :shock: ')"><img src="https://cdn.peanoo.com/ASkyo/images/smilies/icon_eek.gif" alt="" /></a>
<a href="javascript:grin(' :???: ')"><img src="https://cdn.peanoo.com/ASkyo/images/smilies/icon_confused.gif" alt="" /></a>
<a href="javascript:grin(' :cool: ')"><img src="https://cdn.peanoo.com/ASkyo/images/smilies/icon_cool.gif" alt="" /></a>
<a href="javascript:grin(' :lol: ')"><img src="https://cdn.peanoo.com/ASkyo/images/smilies/icon_lol.gif" alt="" /></a>
<a href="javascript:grin(' :mad: ')"><img src="https://cdn.peanoo.com/ASkyo/images/smilies/icon_mad.gif" alt="" /></a>
<a href="javascript:grin(' :twisted: ')"><img src="https://cdn.peanoo.com/ASkyo/images/smilies/icon_twisted.gif" alt="" /></a>
<a href="javascript:grin(' :roll: ')"><img src="https://cdn.peanoo.com/ASkyo/images/smilies/icon_rolleyes.gif" alt="" /></a>
<a href="javascript:grin(' :wink: ')"><img src="https://cdn.peanoo.com/ASkyo/images/smilies/icon_wink.gif" alt="" /></a>
<a href="javascript:grin(' :idea: ')"><img src="https://cdn.peanoo.com/ASkyo/images/smilies/icon_idea.gif" alt="" /></a>
<a href="javascript:grin(' :arrow: ')"><img src="https://cdn.peanoo.com/ASkyo/images/smilies/icon_arrow.gif" alt="" /></a>
<a href="javascript:grin(' :neutral: ')"><img src="https://cdn.peanoo.com/ASkyo/images/smilies/icon_neutral.gif" alt="" /></a>
<a href="javascript:grin(' :cry: ')"><img src="https://cdn.peanoo.com/ASkyo/images/smilies/icon_cry.gif" alt="" /></a>
<a href="javascript:grin(' :mrgreen: ')"><img src="https://cdn.peanoo.com/ASkyo/images/smilies/icon_mrgreen.gif" alt="" /></a>
<br/>